export const places = [
  { title: "Y Combinator", logo: "/logos/yc.avif" },
  { title: "IBM", logo: "/logos/ibm.avif" },
  { title: "Amazon", logo: "/logos/amazon.avif" },
  { title: "Meta", logo: "/logos/meta.avif" },
  { title: "University of Pennsylvania & Wharton", logo: "/logos/penn.avif" },
  { title: "University of Waterloo", logo: "/logos/waterloo.avif" },
  { title: "University of British Columbia", logo: "/logos/ubc.avif" },
  { title: "University of Toronto", logo: "/logos/u of t.avif" },
  { title: "Stanford University", logo: "/logos/stanford.avif" },
  { title: "Oracle", logo: "/logos/oracle.avif" },
  { title: "Nvidia", logo: "/logos/nvidia.avif" },
  { title: "Harvard University", logo: "/logos/harvard.avif" },
  { title: "Google", logo: "/logos/google.avif" },
  { title: "Google Cloud", logo: "/logos/google-cloud.avif" },
  { title: "Google Deepmind", logo: "/logos/google-deepmind.avif" },
  { title: "Microsoft", logo: "/logos/microsoft.avif" },
  { title: "LinkedIn", logo: "/logos/linkedin.avif" },
  { title: "Dell", logo: "/logos/dell.avif" },
  { title: "Coinbase", logo: "/logos/coinbase.avif" },
  { title: "Columbia University", logo: "/logos/columbia_u.avif" },
  { title: "Vanderbilt University", logo: "/logos/vanderbilt.avif" },
  { title: "U.C Berkeley", logo: "/logos/uc_berkeley.avif" },
  { title: "Silicon Valley Fellowship", logo: "/logos/svf.avif" },
  { title: "Western University", logo: "/logos/western.avif" },
  { title: "University of Alberta", logo: "/logos/ualberta.avif" },
  { title: "University of Ottawa", logo: "/logos/uottawa.avif" },
  // { title: "University of Notre Dame", logo: "/logos/" },
  { title: "Techstars", logo: "/logos/techstars.avif" },
  { title: "buildspace", logo: "/logos/buildspace.avif" },
  { title: "AI Circle (ai-circle.org)", logo: "/logos/ai circle.avif" },
  { title: "TEDx", logo: "/logos/tedx.avif" },
];
