export const places = [
  { title: "Y Combinator", logo: "/logos/yc.png" },
  { title: "IBM", logo: "/logos/ibm.png" },
  { title: "Amazon", logo: "/logos/amazon.png" },
  { title: "Meta", logo: "/logos/meta.webp" },
  { title: "University of Pennsylvania & Wharton", logo: "/logos/penn.png" },
  { title: "University of Waterloo", logo: "/logos/waterloo.png" },
  { title: "University of British Columbia", logo: "/logos/ubc.png" },
  { title: "University of Toronto", logo: "/logos/u of t.png" },
  { title: "Stanford University", logo: "/logos/stanford.webp" },
  { title: "Oracle", logo: "/logos/oracle.png" },
  { title: "Nvidia", logo: "/logos/nvidia.png" },
  { title: "Harvard University", logo: "/logos/harvard.png" },
  { title: "Google", logo: "/logos/google.png" },
  { title: "Google Cloud", logo: "/logos/google-cloud.png" },
  { title: "Google Deepmind", logo: "/logos/google-deepmind.png" },
  { title: "Microsoft", logo: "/logos/microsoft.png" },
  { title: "LinkedIn", logo: "/logos/linkedin.webp" },
  { title: "Dell", logo: "/logos/dell.png" },
  { title: "Coinbase", logo: "/logos/coinbase.png" },
  { title: "Columbia University", logo: "/logos/columbia_u.png" },
  { title: "Vanderbilt University", logo: "/logos/vanderbilt.png" },
  { title: "U.C Berkeley", logo: "/logos/uc_berkeley.png" },
  { title: "Silicon Valley Fellowship", logo: "/logos/svf.png" },
  { title: "Western University", logo: "/logos/western.png" },
  { title: "University of Alberta", logo: "/logos/ualberta.png" },
  { title: "University of Ottawa", logo: "/logos/uottawa.png" },
  // { title: "University of Notre Dame", logo: "/logos/" },
  { title: "Techstars", logo: "/logos/techstars.png" },
  { title: "buildspace", logo: "/logos/buildspace.png" },
  { title: "AI Circle (ai-circle.org)", logo: "/logos/ai circle.jpg" },
  { title: "TEDx", logo: "/logos/tedx.png" },
];
